### ISSUE TITLE
Blender script for Obj3D

### ISSUE THREAD

**Issue by shubham0704** [zhixuan-lin/G-SWM#27]
Hi All,
I want to also save the state and positions of objects and their parametric values for shape and size given by blender to evaluate physics of my video generation model. Please can you share the script with me.

**Comment by zhixuan-lin** [comment]
Hi Shubham,

You can download the code here: [3D-Interactions-Dataset.zip](https://github.com/zhixuan-lin/G-SWM/files/15402867/3D-Interactions-Dataset.zip). It is based on [CLEVR](https://github.com/facebookresearch/clevr-dataset-gen) and you can refer to that repo for how to run the code. There is also a newer [CLEVRER](http://clevrer.csail.mit.edu/) dataset that is pretty similar to ours, so you may consider directly using that dataset.

I hope this helps!

**Comment by shubham0704** [comment]
Hi Zhixuan,
thanks a lot for the quick reply! congratulations on the G-SWM submission. I will look at the links that you have shared with me.
