### ISSUE TITLE
Link for pre-trained models seems broken

### ISSUE THREAD

**Issue by mbchang** [zhixuan-lin/G-SWM#3]
Hi, it seems that clicking on the google drive link (https://drive.google.com/drive/directorys/1gyuU5u4is37N7m0CBmZ83RKcELPB5wy5?usp=sharing) for the pre-trained models leads to the following error message.

![image](https://user-images.githubusercontent.com/6439365/99865149-a929b300-2b5c-11eb-8ac3-f3b08ce1487f.png)

Has the link changed?

Thanks!

**Comment by zhixuan-lin** [comment]
Hi @mbchang,

I guess google drive have updated their URL format for folders (`directorys -> folders`). I have updated the link and it should work now.
